id: P009240
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN5078
  title: དགེ་སློང་དཔལ་མོའི་མཛད་རྣམ་ཤེལ་དཀར་ཕྲེང་བ།
  author: ''
  volumes:
    24991de31a154136b60ec9348c5411ab:
      image_group_id: I3CN5080
      title: ''
      volume_number: 1
      total_pages: 110
