id: P009240
initial_creation_type: ocr
created_at: 23/03/2020
last_modified_at: 2021-12-19 19:29:32.517939
source_metadata:
  id: bdr:W3CN5078
  title: དགེ་སློང་དཔལ་མོའི་མཛད་རྣམ་ཤེལ་དཀར་ཕྲེང་བ།
  author: ''
  volumes:
    24991de31a154136b60ec9348c5411ab:
      image_group_id: I3CN5080
      title: ''
      volume_number: 1
      total_pages: 110
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
