id: IA4E3A529
legacy_id: P009240
ocr_import_info:
  bdrc_scan_id: W3CN5078
  source: bdrc
  ocr_info:
    timestamp: '2020-03-23T08:32:23'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-27T11:57:26.752157+00:00'
last_modified: 2022-08-27 19:57:34.888049
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W3CN5078
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW3CN5078
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: དགེ་སློང་དཔལ་མོའི་མཛད་རྣམ་ཤེལ་དཀར་ཕྲེང་བ།
  author: གསེར་ཁྲི་བྲག་དཀར་རིན་ཆེན་གསེར་ཆོས་དགེ་བློ་བཟང་བསྟན་དར།
statistics:
  ocr_word_mean_confidence_index: 0.9151804921077012
  ocr_word_median_confidence_index: 0.9800000190734863
quality: null
bases:
  I3CN5080:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN5080
      total_pages: 110
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I3CN5080.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9151804921077012
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
